"""Add default now to updated_at

Revision ID: 1673c25d1c3b
Revises: f3a84fd4bf1a
Create Date: 2025-12-03 04:57:04.872903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1673c25d1c3b'
down_revision: Union[str, Sequence[str], None] = 'f3a84fd4bf1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
