"""Initial tables

Revision ID: 2dce7665a51d
Revises: 
Create Date: 2025-12-02 16:48:55.574723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dce7665a51d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('fbref_id', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fbref_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('fbref_id', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fbref_id')
    )
    op.create_index(op.f('ix_teams_title'), 'teams', ['title'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fbref_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_xg', sa.Float(), nullable=True),
    sa.Column('away_xg', sa.Float(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('details_parsed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fbref_id')
    )
    op.create_index(op.f('ix_matches_date'), 'matches', ['date'], unique=False)
    op.create_index(op.f('ix_matches_season'), 'matches', ['season'], unique=False)
    op.create_table('player_match_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('position', sa.String(length=5), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('goals', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('assists', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('shots', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('shots_on_target', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('xg', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('npxg', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('xa', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('touches', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('passes_completed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('passes_attempted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('progressive_carries', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tackles', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('interceptions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('blocks', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('other_stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uix_match_player_stat')
    )
    op.create_index(op.f('ix_player_match_stats_match_id'), 'player_match_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_player_match_stats_player_id'), 'player_match_stats', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_match_stats_player_id'), table_name='player_match_stats')
    op.drop_index(op.f('ix_player_match_stats_match_id'), table_name='player_match_stats')
    op.drop_table('player_match_stats')
    op.drop_index(op.f('ix_matches_season'), table_name='matches')
    op.drop_index(op.f('ix_matches_date'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_teams_title'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('players')
    op.drop_table('leagues')
    # ### end Alembic commands ###
