"""Add fbref_id to league model

Revision ID: dbbfa436c11c
Revises: 2dce7665a51d
Create Date: 2025-12-02 21:09:47.624739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbbfa436c11c'
down_revision: Union[str, Sequence[str], None] = '2dce7665a51d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('fbref_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'fbref_id')
    # ### end Alembic commands ###
