"""Add server_default to matches.updated_at

Revision ID: f3a84fd4bf1a
Revises: dbbfa436c11c
Create Date: 2025-12-03 04:52:46.904992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a84fd4bf1a'
down_revision: Union[str, Sequence[str], None] = 'dbbfa436c11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
